adicionei meu perfil
Camilotk/desafio_meentoria pull request #3
Opened 2021-09-20 01:31 UTC by bahterista

2021-09-20 02:10 UTC, Camilotk requested changes

2021-09-20 02:10 UTC, Camilotk commented on README.md
> +bla bla bla
Adicionar a descrição aqui.

2021-09-20 02:10 UTC, Camilotk commented on README.md
> +**Link Github**: [Link](link do seu perfil)
Adicionar o link para seu perfil.

```
[Link](https://github.com/bahterista)
```

2021-09-20 02:10 UTC, Camilotk commented on README.md
> +**Cidade**: Sua Cidade ||
Adicionar qual a cidade você mora.

2021-09-22 23:26 UTC, bahterista commented on README.md
> +bla bla bla
Corrigido.

2021-09-22 23:26 UTC, bahterista commented on README.md
> +**Link Github**: [Link](link do seu perfil)
Corrigido.

2021-09-22 23:38 UTC, Camilotk approved these changes

2021-09-22 23:41 UTC, merged